### PR TITLE
Recipe improvements

### PR DESCRIPTION
**Pull request by danimtb**
- Use conan tools to unify steps
- Use 7z_installer to unpack sources
- Rename source folder to 'sources' for better manipulation
- Add options for `ARMA_USE_LAPACK` and `ARMA_USE_BLAS`

### CODE REVIEW

**Comment by danimtb** [comment]
This PR fixes https://github.com/conan-io/conan/issues/2117

**Comment by danimtb** [comment]
Note that the recipe is not complete.

Optional dependencies of LAPACK and BLAS are still not done (ARMA_USE_LAPACK=True, ARMA_USE_BLAS=True)

I encourage you to continue with the development and try to submit it to conan-center on bintray ( See [Contributing packages to conan-center](http://conanio.readthedocs.io/en/latest/packaging/bintray/conan_center_guide.html)) as the Armadillo library is missing and this is a great first step.
That would be awesome! 😃

**Comment by Yevgnen** [comment]
Hi, thanks for you work.

> Optional dependencies of LAPACK and BLAS are still not done (ARMA_USE_LAPACK=True, ARMA_USE_BLAS=True)

Is that mean a proper way to solve this is to create conan version of `blas` and `lapack` and make the `armadillo` recipe depend on them just like the `7z_installer`?

**Comment by danimtb** [comment]
Yes @Yevgnen, you would have to creacte thos packages.

Fortunately I am working on OpenBLAS which you can use as your BLAS dependency: https://github.com/danimtb/conan-openblas

**Comment by danimtb** [comment]
@Yevgnen did you have the time to check this?

**Comment by Yevgnen** [comment]
@danimtb Hi, sorry for late reply. Now I got this

```
tar: Error opening archive: Failed to open 'armadillo-8.300.0.tar'
Armadillo/8.300.0@demo/testing: WARN: Trying to remove dirty source folder
Armadillo/8.300.0@demo/testing: WARN: This can take a while for big packages
ERROR: Armadillo/8.300.0@demo/testing: Error in source() method, line 34
	self.run("tar -xvf %s" % self.source_tar_file)
	ConanException: Error 256 while executing tar -xvf armadillo-8.300.0.tar
```

Why are there *two* `tar` commands there?

**Comment by danimtb** [comment]
Hi @Yevgnen 

Inside the `tar.xz` downloaded file there is another `.tar` file.

I thought tar tool would NOT untar files recursively as `7z `can't untar recursively, but I must be wrong.

Just remove the second tar command and it should be fine

**Comment by Yevgnen** [comment]
@danimtb Hi, after removing the second `tar` and moving the `os.unlink`, seems fine now.

```
        if self.settings.os == "Windows":
            self.run("7z x %s" % self.source_tarxz_file)
            self.run("7z x %s" % self.source_tar_file)
            os.unlink(self.source_tar_file)
        else:
            self.run("tar -xvf %s" % self.source_tarxz_file)

        os.unlink(self.source_tarxz_file)
```

Do you mind making this a new commit?

**Comment by danimtb** [comment]
Done!

**Pull request merged**
